/* Implement Following Hierarchy 

			class : student                                             
			data members : roll_no,name
			|
			|
			v	
			class : test                                    class :sports 
			data members : marks1 , marks2                  data members : score
			|                                                       |
			|                                                       |
			v      							|
   			  	                                            	v
			class : result  <---------------------------------------  
			data member:total
*/

